services:

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  fastapi:
    build:
      context: api/
    hostname: api
    container_name: api
    restart: always
    expose:
      - 8000
    volumes:
      - type: bind
        source: ./api/logs.log
        target: /app/logs.log