services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    ulimits:
      nofile:
        soft: 122880
        hard: 122880

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - my-db:/data/db

volumes:
  my-db: