
# Base image
FROM node:bookworm

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm i sharp
# Copy all other source files
COPY . .

RUN npm run build

CMD ["npm", "run", "start"]
